# Generated by Django 4.2.4 on 2023-12-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_upload', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnails', models.ImageField(upload_to='thumbnails/')),
                ('link', models.URLField()),
            ],
        ),
    ]
